redhat-developer/app-services-ui

static/configs/terms-conditions-spec.json, webpack.prod.js
Adding specification for terms and conditions. Purpose of this change is to host this file remotely and access it from multiple clients like CLI, UI etc.
In for go files structure will look like:
```
type TermsAndConditionsSpec struct {
Kafka           ServiceTermsSpec `json:"kafka"`
ServiceRegistry ServiceTermsSpec `json:"service-registry"`
}
type ServiceTermsSpec struct {
EventCode         string `json:"EventCode"`
SiteCode          string `json:"SiteCode"`
StopOnTermsChange bool   `json:"StopOnTermsChange"`
}
```
We might need to add that to SDK along with AMS SDK
=> chore: terms and conditions spec

src/AppEntry.tsx
This is to prevent refreshes in routes handled by kafka-ui to break the app for calls to useModal complaining about a missing ModalProvider
=> fix: provide a global ModalProvider

.github/workflows/node.js.yml
For some reason @ajaypratap003 merged the lint into the main build - this splits it back out again and adds the formatting checking back in
=> fix: split the lint job back out again

src/locales/kafka-ui.json
Adding translation for cancel modal in the Access tab
=> Adding translation for cancel modal in the Access tab

tsconfig.json
Running project with all federated UIs source code hangs both Vscode and InteliJ
This happens due to large number of typescript files that are not excluded
=> fix: vscode hangs when trying to run project with local dev

config/config.json, webpack.dev.js
console.redhat.com is now being served with a CSP header that disables any javascript coming from sources not listed in the policy.
We load the federated modules from localhost (many ports) when running the local dev environment, the CSP breaks this behavior.
To fix it, we need to make the app ask for the resources through a pre-defined path, and then proxy the request to the right local server.
To do this the config.json contains a new basePath property that specifies the pre-defined path mentioned before, and a new proxyTarget property
that contains where the proxy should point to fetch the resources for all requests that contains the pre-defined path.
=> fix: make the local development workflow work again

package-lock.json, package.json
In latest `kafka-instance-sdk`, there are major changes which breaks the kafka-ui app and topics api call (admin api).
This is temporary fix. We need to fix all the changes with latest version of `kafka-instance-sdk` 
https://issues.redhat.com/browse/MGDSTRM-7832
=> downgrade  sdk (kafka-instance-sdk) which breaks admin api on dashboard page

src/app/AppRoutes.tsx, src/app/pages/ServiceRegistry/SettingsPage.tsx, src/app/pages/ServiceRegistry/utils.ts
This is a new page in the RHOSR data plane (admin only).  It's a peer of the Access and Global Rules pages.
=> Added the Settings page for RHOSR data plane

static/configs/service-constants.json
UI implemented new method for calculating quota but we still need to fix existing RHOAS CLI instances that rely on the values that will be wrong. I will be making change in CLI to fix it but users will not get that instantly
=> fix: rhoas cli backwards compatiblity by updating changes

src/app/pages/Kafka/kafka-instance.ts
**Why**
When deploying the UI in a different environment from stage or production the Kafka admin server route and/or protocol can change and therefore we must be able to re-configure it in the UI
Blocked: https://github.com/redhat-developer/app-services-ui-shared/pull/117
=> chore: make the Kafka admin server URL configurable

src/app/AppRoutes.tsx
This fixes the case where some deep routes have something in common with a less deep url.
Say we have the two following exact routes:
/overview
/streams/overview
If the user navigates to /streams/overview, both routes will match, but only the last one will be triggered by the wrapping Switch. If we were to reverse the order, it would be the /overview route to be triggered which we don't want.
So it's important to always sort the routes by specificity when adding them to the list of routes.
=> fix: reorder routes from less specific to more specific ones

config/config.json
I'm not really sure what will happen in the browser when there are duplicate keys in a JSON file, but based on what I'm seeing on qaprodauth it looks like the second one wins.  In any case, I've removed the duplicate (empty) config.
=> Fixed a problem with duplicate "ads" section in the config

src/app/pages/Kafka/kafka-instance.ts
This PR enables us to use admin server url that is returned by backend. 
This change was also introduced into CLI and have been running in production for long time. 
We need this to enable testing with kas-installer as well as to future proof admin server api requests for stage and prod. 
1. Select your kafka on the list. You will be redirected to metrics view
2. Check if metrics view works fine (it can be empty if your kafka is new)
3. Navigate to topics. 
4. You should be able to see and view the topics. If no topics create new one.
=> fix: use backend admin server url

README.md
There were so many requests recently related to be able to run UI locally with custom URLs for the service. This was deemed to be impossible before but it have been proven working right now with number of fixes merged into the UI itself. 
I would like to put some initial documentation for this that can be extended later
=> fix: add kas-installer section

webpack.dev.js
- allow `useAgent` to be set to `false` (for use without HttpProxy)
- enable advanced TLS options via environment when using HTTPS
=> Enable use with kas-installer (set useAgent via env, HTTPS via `server`)

src/app/pages/ServiceRegistry/FederatedApicurioComponent.tsx, src/app/pages/ServiceRegistry/utils.ts
I have updated the RHOSR data plane `Settings` page to send a toast alert whenever the user changes one of the settings.  In order to use the shared app-services-ui `Alert` hook, I need to inject it into the data plane layer's federated components.
=> Inject alerts into the RHOSR data plane

src/app/pages/ServiceRegistry/ArtifactVersion.tsx
The artifact version page in the registry data plane has been modified to allow users to be able to change the ownership of an artifact.  In order to display a dropdown of users when doing this, we need the list of principals in the org.  These are passed in, same as in the Access page.
=> Pass the principals to the artifact version page

src/app/App.tsx
This change updates the app navigation event handling, navId is deprecated apparently.  This change pulls the URL out of the contained DOMEvent and adjusts it so that it will ideally match one of the defined application routes.
Thanks @Hyperkid123 for tracking this down :smile:
=> MGDCTRS-1519 fix: update nav event handling

src/app/hooks/usePrincipals.ts, src/app/pages/ServiceRegistry/FederatedApicurioComponent.tsx
Passing a function to the federate component didn't work consistently.  Sometimes it worked and sometimes it didn't. Likely I don't quite understand how callback functions are created and passed around in a react application.
This time, I'm trying to fix the issue using react constructs, specifically `useEffect` and `useState`.  Now the principal array is a state variable in the component, and that state variable is updated whenever the `getAllPrincipals` function changes.  If I understand how `usePrincipal` is written (and how React's `useCallback` works with memoized functions) then the `getAllPrincipals` function should change only when the underlying data changes (the data is fetched asynchronously).  When that happens, the new effect should fetch the principals using that function …
=> Try to fix the principal issue take 2

src/app/pages/ServiceRegistry/ArtifactVersion.tsx, src/app/pages/ServiceRegistry/SrsLayout.tsx
Need to include both `groupId` and `version` as params to `SrsLayout` so that the federated apicurio component is recreated when either of those params changes.
=> Artifact version page must rerender when the `version` changes

src/app/AppRoutes.tsx
This change removes the service preview banner from the connectors service app.
=> chore: MGDCTRS-1775 remove service preview banner
