src/app/pages/ServiceRegistry/ServiceRegistryPage.tsx
Depends on https://github.com/bf2fc6cc711aee1a0c2a/srs-ui/pull/213
Signed-off-by: Srijita Mukherjee <srmukher@redhat.com>
=> Pass token URL for Service Registry Auth

src/app/AppRoutes.tsx
Remove Dev Preview banner from Service Registry pages
=> Remove Dev Preview banner from Service Registry pages

src/app/pages/ServiceRegistry/DownloadArtifacts.tsx, src/app/pages/ServiceRegistry/FederatedApicurioComponent.tsx, src/app/pages/ServiceRegistry/ServiceRegistryPage.tsx, src/app/pages/ServiceRegistry/SrsLayout.tsx
Let's merge other PRs first.
https://github.com/bf2fc6cc711aee1a0c2a/srs-ui/pull/359
https://github.com/Apicurio/apicurio-registry/pull/2065
=> Add download artifacts feature

src/app/pages/Kafka/metricsApi.ts
Integrating Incoming Message Rate API
=> Integrating Incoming Message Rate API

static/configs/terms-conditions-spec.json
Update event code as `register` for service registry
=> update event code for service registry

src/app/utils/keycloak/keycloakUtils.ts
This is a nasty way to handle this, but we will remove this code soon anyway.
=> fix: wait after setting the refresh token

src/app/AppRoutes.tsx, src/app/components/FederatedModule/FederatedModule.tsx, src/app/components/InstanceDrawer/InstanceDrawer.tsx, src/app/pages/Kas/KasPage.tsx, src/app/pages/Resources/QuickStartLoaderFederated.tsx, src/app/pages/Resources/ResourcesPage.tsx, src/app/pages/ServiceAccounts/ServiceAccountsPage.tsx, src/app/pages/ServiceRegistry/FederatedApicurioComponent.tsx, src/app/pages/ServiceRegistry/ServiceRegistrySchemaMapping.tsx, src/app/pages/ServiceRegistry/SrsLayout.tsx
Fixes [MGDSTRM-6880](https://issues.redhat.com/browse/MGDSTRM-6880)
=> fix: avoid re-render of the FederatedModule components

src/app/components/FederatedModule/FederatedModule.tsx, src/app/components/InstanceDrawer/InstanceDrawer.tsx, src/app/pages/Kafka/KafkaMainView.tsx, src/app/pages/Kafka/KafkaRoutes.tsx
Fixes [MGDSTRM-6612](https://issues.redhat.com/browse/MGDSTRM-6612)
Requires https://github.com/bf2fc6cc711aee1a0c2a/kas-ui/pull/988
=> fix: make the drawer work when federated

package-lock.json, package.json, src/app/pages/Overview/OverviewPage.tsx
https://issues.redhat.com/browse/MGDX-17
Let's merge ui-components PR first and update version in this PR.
https://github.com/redhat-developer/app-services-ui-components/pull/124
=> Fixed service registry url on overview page

src/app/components/PrincipalsProvider/PrincipalsProvider.tsx, src/app/pages/ServiceRegistry/FederatedApicurioComponent.tsx, src/app/pages/ServiceRegistry/RolesPage.tsx
https://issues.redhat.com/browse/MGDSR-69
=> [Bug] Fixed principals data not loading issue on roles modal

config/config.json
https://issues.redhat.com/browse/MGDCTRS-277
=> MGDCTRS-277 Update Debezium connector version to 1.9.0.Alpha1

config/config.json
https://issues.redhat.com/browse/MGDCTRS-417
=> MGDCTRS-417: Update staging API endpoint

config/config.json
follow-up to https://github.com/redhat-developer/app-services-ui/pull/355  all the env.
=> MGDCTRS-335:Use single federated module configuration for DBZ UI

src/app/pages/Kafka/kafka-instance.ts
In recent sdk `/rest` is already there so we need to remove extra `/rest`
https://issues.redhat.com/browse/MGDSTRM-7832
=> Fix adminUrl issue

src/app/pages/Kafka/kafka-instance.ts
Reverts redhat-developer/app-services-ui#385
Reverting this PR. Noticed there are major changes in recent sdk which breaks the kafka-ui app.
I'll degrade sdk version in app-services-ui so that topics api will work on Dashboard page which is braking with latest sdk.
=> Revert "Fix adminUrl issue"

package-lock.json, package.json, src/app/utils/keycloak/keycloakUtils.ts
* Disable iframe logins
* Upgrade to 17.0.0
=> fix: make keycloak js work with enhanced tracking protection

src/app/hooks/quota.ts, src/app/providers/config/ServiceConstants.ts, static/configs/service-constants.json
https://issues.redhat.com/browse/MGDSTRM-7932
=> fix standard quota issue, update quota id

src/AppEntry.tsx, src/app/AppRoutes.tsx, src/app/pages/KafkaOverview/KafkaOverviewPage.tsx, src/app/pages/KafkaOverview/index.ts
=> feat: add an overview page to the streams section

src/app/hooks/quota.ts
Adding error for catching up situation when ams errors are happening
=> fix: add error log

config/config.json
https://issues.redhat.com/browse/MGDCTRS-356
update the prod backend URL for COS to https://wxn4abbc8bqvxcy6unfe.api.openshift.com/
=> MGDCTRS-356: update the backend url for RHOC prod

config/config.json
Revert cos prod bakend endpoint.
=> MGDCTRS-356: revert cos backend endpoint

package-lock.json, package.json, src/AppEntry.tsx, src/app/pages/KafkaOverview/KafkaOverviewPage.tsx, src/app/pages/Overview/OverviewPage.tsx
Integrate UI components for Kafka overview and Application overview page from app-services-ui-components
=> Integrate UI components for kafka overview and Application overview page from app-services-ui-components

.eslintrc, package-lock.json, package.json
https://issues.redhat.com/browse/MGDSTRM-8457
=> Add deprecation eslint rule

README.md, config/config.json, hack/checkout-repos.sh, src/app/AppRoutes.tsx, src/app/pages/APIDesigner/ApiDesignerEditorPage.tsx, src/app/pages/APIDesigner/ApiDesignerHomePage.tsx
We're creating a new managed service called API Designer.  Phase 1 is exclusively new UI pages (no back-end components).  This PR adds route and sets up config for API Designer.
=> Adding API Designer routes and config

config/config.json
Previous values were not quite correct.  I think these **are** the correct endpoints for the ads-editors iframe content.
=> Updated the ads-editors endpoint for all environments

src/app/pages/Kafka/ConnectedMetrics.tsx, src/app/pages/Kafka/kafka-instance.ts
**What this PR does / why we need it:**
> Fix `something went wrong` issue on clicking the Kafka instance during the creation 
**Which issue(s) this PR fixes**
https://issues.redhat.com/browse/MGDSTRM-9025
=> fix something went wrong issue

package-lock.json, package.json
Updating the app-services-ui-component version manually since the renovate bot fails to update it, due to some failing job
=> Update app-services-ui-component version to latest

src/app/hooks/modal.ts, src/app/pages/Kas/KasPage.tsx, src/app/pages/ServiceRegistry/ServiceRegistryPage.tsx
https://issues.redhat.com/browse/MGDX-173
=> integrate terms and conditions modal

package-lock.json, package.json, src/AppEntry.tsx
Add localization of connection-tab
=> Add localization of connection-tab

package-lock.json, package.json, src/AppEntry.tsx, src/app/pages/KafkaOverview/KafkaOverviewPage.tsx
Integrate AWS Marketplace
**Which issue the PR fixes**
https://issues.redhat.com/browse/MGDSTRM-9272
=> Intergate AWS MarketPlace

package-lock.json, package.json, src/app/pages/DataScience/DataSciencePage.tsx, src/app/pages/Kafka/KafkaFederatedComponent.tsx, src/app/pages/Kafka/KafkaMainView.tsx, src/app/pages/Kafka/KafkaRoutes.tsx, src/app/pages/Kafka/Settings.tsx, src/app/pages/Kafka/SettingsTab.tsx, src/app/pages/Kafka/api/fetchSettings.ts, src/app/pages/Kafka/api/index.ts, src/app/pages/Kafka/index.ts, src/locales/kafka-ui.json
Integrate the Settings tab from app-services-ui-components
Related to https://issues.redhat.com/browse/MGDSTRM-8810
=> Integrate settings tab

package-lock.json, src/AppEntry.tsx, src/app/pages/Overview/OverviewPage.tsx
Update the UI component version
Add a translation file for the latest version of the connection tab
Integrated API Designer card in the overview page
=> Integrate api card

src/app/pages/DataScience/DataSciencePage.tsx
jira ref: https://issues.redhat.com/browse/RHCLOUD-18476
DataScience page updates: https://github.com/redhat-developer/app-services-ui-components/pull/349
=> Implement RHODS clusters info data fetching.

src/AppEntry.tsx
Add translation for Kafka topic
=> Add translation for Kafka topic

src/app/pages/DataScience/DataSciencePage.tsx
removing single quote to fix RHODS-7968
=> removing single quote to fix RHODS-7968

package-lock.json, package.json, src/app/pages/Overview/OverviewPage.tsx, src/locales/kas-ui.json
- Update ui-components version
- update service account description
=> Update ui-components version

src/app/AppRoutes.tsx
revert RHOSR route and API Designer route
=> revert RHOSR and API Designer
